version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.11
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.type=single-node
      - script.max_compilations_per_minute=1000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - esrally
    ports:
      - 9200:9200
        
networks:
  esrally:
    driver: bridge

volumes:
  elasticsearch-data:
